sio_gsb_homepage:
    path:     /index
    defaults: { _controller: SioGsbBundle:Default:index }
sio_gsb_connexion:
    path:    /connexion
    defaults: { _controller: SioGsbBundle:Default:connexion}
sio_gsb_dashboard:
    path:    /dashboard
    defaults: {_controller: SioGsbBundle:Default:dashboard}
sio_gsb_calendaradmin:
    path: /calendaradmin
    defaults: {_controller: SioGsbBundle:Default:calendaradmin}
sio_gsb_detailEvent:
    path: /detailEvent/{chaine}/{valeur}
    defaults: {_controller: SioGsbBundle:Default:detailEvent}